- name: Elastic events
  hosts: localhost
  sources:
    - elastic:
        elastic_host: https://localhost.com
        elastic_username: elastic
        elastic_password: Jlgn@1985
        elastic_index_pattern: filebeat-*
        query: |
          term:
            container.name.keyword: nginx
        interval: 5

  rules:
    - name: Debug event
      condition: event.ecs is defined and event.nginx.log_level == "error"
      action:
        debug:
